### ISSUE TITLE
Any chance of a 4.0.1 update?

### ISSUE THREAD

**Issue by weavejester** [pixijs/pixi-closure-compiler#2]
It would be nice to have externs for Pixi 4.0.1. I've tried automatically generating externs, but keep running into problems. If I manage to solve them, I'll link the externs I created.

**Comment by markknol** [comment]
+1 for updated externs!

**Comment by zh99998** [comment]
+1

**Comment by rtalon83** [comment]
Yes.
https://github.com/pixijs/pixi-closure-compiler/pull/3
